[workspace]
publish = false
changelog_config = ".cliff.toml"
changelog_update = true
dependencies_update = false
git_tag_enable = true
git_tag_name = "{{ version }}"
pr_labels = ["release"]
semver_check = false
