[workspace]
publish = false
publish_no_verify = true
changelog_config = ".cliff.toml"
changelog_update = true
dependencies_update = false
pr_labels = ["release"]
git_tag_enable = false
semver_check = false
